name: Linux C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build 
      run: gcc project_main.c -o project_main.exe
    - name: Run
      run: ./project_main.exe
